# Name of this GitHub Actions workflow.
name: Semgrep SAST

on:
  # Scan changed files in PRs (diff-aware scanning):
  pull_request: {}

  # Scan on-demand through GitHub Actions interface:
  workflow_dispatch: {}

  # Scan mainline branches and report all findings:
  # Ensure you have the correct branch/es for your project
  # Recommend only setting the default branch on push, or branches you push to frequently
  push:
    branches: ["main"]

  # Schedule the CI job (this method uses cron syntax):
  #schedule:
    #- cron: '0 0 1 * *' # Sets Semgrep to scan on the 1st of every month at 12:00 AM UTC.
    # It is recommended to change the schedule to a random time.
jobs:
  semgrep:
    name: SAST Scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep

    steps:
    - uses: actions/checkout@v4
    - name: Semgrep CI for pull request
      run: |
        semgrep ci --sarif > semgrep.sarif
      if: ${{ github.event_name == 'pull_request' }}
      env:
        SEMGREP_REPO_URL: ${{ github.server_url }}/${{ github.repository }}
        SEMGREP_REPO_DISPLAY_NAME: ${{ github.repository }}/${{ github.base_ref }}
        SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    - name: Semgrep CI for others
      run: semgrep ci --sarif > semgrep.sarif
      if: ${{ github.event_name != 'pull_request' }}
      env:
        SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
        SEMGREP_REPO_DISPLAY_NAME: ${{ github.repository }}/${{ github.ref_name }}
    - name: Upload SARIF file for GitHub Advanced Security Dashboard
      uses: github/codeql-action/upload-sarif@v3
      with: 
        sarif_file: semgrep.sarif
      if: always()
